/**
 * The icon set, as SVG paths.
 *
 * Vuetify's default is the Material Design icon *font*: about 4 MB of font
 * files and a 670 kB stylesheet defining every one of 7,000 glyphs, of which
 * this interface uses seventy-one. Importing those seventy-one as paths keeps
 * every  in the components working and drops the whole font.
 *
 * Adding an icon means adding it to this list; an unknown name renders as a
 * question mark rather than nothing, so the omission is visible.
 */
import { h } from 'vue';
import type { IconSet, IconProps } from 'vuetify';
import { VSvgIcon } from 'vuetify/components';
import {
  mdiAccount,
  mdiAccountMultiple,
  mdiAccountStar,
  mdiAccountStarOutline,
  mdiAlphaXBox,
  mdiArrowRight,
  mdiBackspaceOutline,
  mdiBellRingOutline,
  mdiCheck,
  mdiCheckDecagramOutline,
  mdiCounter,
  mdiAccountOutline,
  mdiThermometer,
  mdiPaletteOutline,
  mdiContrastCircle,
  mdiBrightness6,
  mdiImageOutline,
  mdiSortVariant,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiUndoVariant,
  mdiHistory,
  mdiCodeJson,
  mdiFileDelimitedOutline,
  mdiDownloadOutline,
  mdiCheckCircleOutline,
  mdiAlertCircleOutline,
  mdiVectorLink,
  mdiWeatherSunset,
  mdiClockCheckOutline,
  mdiCalendarWeek,
  mdiFormatLetterCase,
  mdiCalculatorVariant,
  mdiCellphone,
  mdiChartBellCurve,
  mdiChartBoxOutline,
  mdiChartTimelineVariant,
  mdiChevronDoubleUp,
  mdiCircleOutline,
  mdiClockFast,
  mdiClose,
  mdiCog,
  mdiCogOutline,
  mdiCommentMultipleOutline,
  mdiConsole,
  mdiContentSave,
  mdiDatabase,
  mdiDownload,
  mdiEarth,
  mdiFileMultipleOutline,
  mdiFire,
  mdiFormatListBulleted,
  mdiGoogle,
  mdiHandBackRightOutline,
  mdiHeadphones,
  mdiHeartPulse,
  mdiHelpCircleOutline,
  mdiImage,
  mdiInstagram,
  mdiLan,
  mdiLightbulbOnOutline,
  mdiLinkVariant,
  mdiMagnify,
  mdiMapMarker,
  mdiMovieOpen,
  mdiMusicNote,
  mdiNewBox,
  mdiOpenInNew,
  mdiPlay,
  mdiPodium,
  mdiPound,
  mdiPowerPlugOutline,
  mdiRadar,
  mdiReddit,
  mdiRefresh,
  mdiRocketLaunch,
  mdiRocketLaunchOutline,
  mdiRss,
  mdiSend,
  mdiShapeOutline,
  mdiSpeedometer,
  mdiSprout,
  mdiTable,
  mdiText,
  mdiThermometerHigh,
  mdiTimerOutline,
  mdiTrendingDown,
  mdiTrendingUp,
  mdiTriangleOutline,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeb,
  mdiWizardHat,
  mdiYoutube,
  mdiNewspaperVariantOutline,
  mdiBookOpenPageVariant,
  mdiMastodon,
  mdiLockOpenVariantOutline,
  mdiLockOutline,
  mdiScaleBalance,
  mdiTagOutline,
  mdiTextShort,
  mdiCloudOutline,
  mdiGithub,
  mdiChartBar,
  mdiClockOutline,
} from '@mdi/js';

const PATHS: Readonly<Record<string, string>> = {
  'mdi-account': mdiAccount,
  'mdi-account-multiple': mdiAccountMultiple,
  'mdi-account-star': mdiAccountStar,
  'mdi-account-star-outline': mdiAccountStarOutline,
  'mdi-alpha-x-box': mdiAlphaXBox,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-backspace-outline': mdiBackspaceOutline,
  'mdi-calculator-variant': mdiCalculatorVariant,
  'mdi-cellphone': mdiCellphone,
  'mdi-chart-bell-curve': mdiChartBellCurve,
  'mdi-chart-box-outline': mdiChartBoxOutline,
  'mdi-chart-timeline-variant': mdiChartTimelineVariant,
  'mdi-chevron-double-up': mdiChevronDoubleUp,
  'mdi-circle-outline': mdiCircleOutline,
  'mdi-clock-fast': mdiClockFast,
  'mdi-close': mdiClose,
  'mdi-cog': mdiCog,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-comment-multiple-outline': mdiCommentMultipleOutline,
  'mdi-console': mdiConsole,
  'mdi-content-save': mdiContentSave,
  'mdi-database': mdiDatabase,
  'mdi-download': mdiDownload,
  'mdi-earth': mdiEarth,
  'mdi-file-multiple-outline': mdiFileMultipleOutline,
  'mdi-fire': mdiFire,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-google': mdiGoogle,
  'mdi-hand-back-right-outline': mdiHandBackRightOutline,
  'mdi-headphones': mdiHeadphones,
  'mdi-heart-pulse': mdiHeartPulse,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-image': mdiImage,
  'mdi-instagram': mdiInstagram,
  'mdi-lan': mdiLan,
  'mdi-lightbulb-on-outline': mdiLightbulbOnOutline,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-magnify': mdiMagnify,
  'mdi-map-marker': mdiMapMarker,
  'mdi-movie-open': mdiMovieOpen,
  'mdi-music-note': mdiMusicNote,
  'mdi-new-box': mdiNewBox,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-play': mdiPlay,
  'mdi-podium': mdiPodium,
  'mdi-pound': mdiPound,
  'mdi-power-plug-outline': mdiPowerPlugOutline,
  'mdi-radar': mdiRadar,
  'mdi-reddit': mdiReddit,
  'mdi-refresh': mdiRefresh,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
  'mdi-rss': mdiRss,
  'mdi-send': mdiSend,
  'mdi-shape-outline': mdiShapeOutline,
  'mdi-speedometer': mdiSpeedometer,
  'mdi-sprout': mdiSprout,
  'mdi-table': mdiTable,
  'mdi-text': mdiText,
  'mdi-thermometer-high': mdiThermometerHigh,
  'mdi-timer-outline': mdiTimerOutline,
  'mdi-trending-down': mdiTrendingDown,
  'mdi-trending-up': mdiTrendingUp,
  'mdi-triangle-outline': mdiTriangleOutline,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-view-grid-outline': mdiViewGridOutline,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-web': mdiWeb,
  'mdi-wizard-hat': mdiWizardHat,
  'mdi-youtube': mdiYoutube,
  'mdi-newspaper-variant-outline': mdiNewspaperVariantOutline,
  'mdi-book-open-page-variant': mdiBookOpenPageVariant,
  'mdi-mastodon': mdiMastodon,
  'mdi-cloud-outline': mdiCloudOutline,
  'mdi-github': mdiGithub,
  'mdi-chart-bar': mdiChartBar,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-lock-open-variant-outline': mdiLockOpenVariantOutline,
  'mdi-bell-ring-outline': mdiBellRingOutline,
  'mdi-format-letter-case': mdiFormatLetterCase,
  'mdi-text-short': mdiTextShort,
  'mdi-counter': mdiCounter,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-check-decagram-outline': mdiCheckDecagramOutline,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-thermometer': mdiThermometer,
  'mdi-palette-outline': mdiPaletteOutline,
  'mdi-contrast-circle': mdiContrastCircle,
  'mdi-brightness-6': mdiBrightness6,
  'mdi-image-outline': mdiImageOutline,
  'mdi-sort-variant': mdiSortVariant,
  'mdi-eye-off-outline': mdiEyeOffOutline,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-undo-variant': mdiUndoVariant,
  'mdi-history': mdiHistory,
  'mdi-code-json': mdiCodeJson,
  'mdi-file-delimited-outline': mdiFileDelimitedOutline,
  'mdi-download-outline': mdiDownloadOutline,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-check': mdiCheck,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-vector-link': mdiVectorLink,
  'mdi-calendar-week': mdiCalendarWeek,
  'mdi-clock-check-outline': mdiClockCheckOutline,
  'mdi-weather-sunset': mdiWeatherSunset,
};

export const svgIcons: IconSet = {
  component: (props: IconProps) =>
    h(VSvgIcon, { ...props, icon: PATHS[String(props.icon)] ?? mdiHelpCircleOutline }),
};

export const aliases = {
  complete: mdiClose,
  cancel: mdiClose,
  close: mdiClose,
  delete: mdiClose,
  clear: mdiClose,
  success: mdiFire,
  info: mdiHelpCircleOutline,
  warning: mdiThermometerHigh,
  error: mdiAlphaXBox,
  prev: mdiArrowRight,
  next: mdiArrowRight,
  checkboxOn: mdiCircleOutline,
  checkboxOff: mdiCircleOutline,
  checkboxIndeterminate: mdiCircleOutline,
  delimiter: mdiCircleOutline,
  sortAsc: mdiTrendingUp,
  sortDesc: mdiTrendingDown,
  expand: mdiChevronDoubleUp,
  menu: mdiFormatListBulleted,
  subgroup: mdiChevronDoubleUp,
  dropdown: mdiChevronDoubleUp,
  radioOn: mdiCircleOutline,
  radioOff: mdiCircleOutline,
  edit: mdiCogOutline,
  ratingEmpty: mdiCircleOutline,
  ratingFull: mdiFire,
  ratingHalf: mdiFire,
  loading: mdiRefresh,
  first: mdiArrowRight,
  last: mdiArrowRight,
  unfold: mdiChevronDoubleUp,
  file: mdiFileMultipleOutline,
  plus: mdiPound,
  minus: mdiBackspaceOutline,
  calendar: mdiTimerOutline,
  treeviewCollapse: mdiChevronDoubleUp,
  treeviewExpand: mdiChevronDoubleUp,
  eyeDropper: mdiMagnify,
  upload: mdiDownload,
  color: mdiImage,
  command: mdiConsole,
  ctrl: mdiConsole,
  space: mdiConsole,
  shift: mdiConsole,
  alt: mdiConsole,
  enter: mdiArrowRight,
  arrowup: mdiTrendingUp,
  arrowdown: mdiTrendingDown,
  arrowleft: mdiArrowRight,
  arrowright: mdiArrowRight,
  backspace: mdiBackspaceOutline,
};
